### ISSUE TITLE
Remove field `mem: &'a M` from Struct Queue

### ISSUE THREAD

**Issue by jiangliu** [rust-vmm/vm-virtio#12]
Currently the Struct Queue is defined as:
```rust
#[derive(Clone)]
/// A virtio queue's parameters.
pub struct Queue<'a, M: GuestMemory> {
    mem: &'a M,

    /// The maximal size in elements offered by the device
    max_size: u16,

    next_avail: Wrapping<u16>,
    next_used: Wrapping<u16>,
}
```
The `mem` field is reference to an object of GuestMemroy. We encountered several issues with this design,
1) we need to explicitly carries the lifetime parameter,
2) we need to explicitly declare the `M` type parameter,
3) it enforces the guest memory object used by the Queue object is the same type, which forbids optimization for enabling memory hotplug, which may have a GuestMemory type and GuestMemory snapshot type.
So how about reverting to the original design by removing field `mem` from struct Queue?

**Comment by bonzini** [comment]
Can you include a patch to understand better?

**Comment by jiangliu** [comment]
> Can you include a patch to understand better?

We encountered this issue when trying to define some structs as
```rust
pub struct VirtioQueueConfig {
    pub queue: Queue,
    pub queue_evt: EventFd,
}

pub struct VirtioDeviceConfig<M: GuestMemory> {
    pub mem: M,
    pub queues: Vec<VirtioQueueConfig>,
    pub ctrl_queue: Option<VirtioQueueConfig>,
    pub intr_group: Arc<Box<dyn InterruptSourceGroup>>,
    legacy_mode: bool,
}
```
And I will post a PR against the vm-virtio crate.

**Comment by bonzini** [comment]
I tried to move vm-virtio to `GuestAddressSpace`, and this was not an issue. (I did need rust-vmm/vm-memory#82, but that was needed even when I tried to rebase on top of the removal of `mem: &'a M`. So I think this is not needed.

**Comment by bonzini** [comment]
https://github.com/bonzini/vm-virtio/tree/address-space.
