### ISSUE TITLE
virtio-queue doctests fail due to build-time inclusion conditionals

### ISSUE THREAD

**Issue by slp** [rust-vmm/vm-virtio#136]
While building doctests, neither the `test` nor the `doctest` features are enabled. This means features gated behind `[cfg(test...)]` will not be available in doctests code. In `virtio-queue` case, this has an impact on [mock visibility](https://github.com/rust-vmm/vm-virtio/blob/main/crates/virtio-queue/src/lib.rs#L34) and some [Descriptor helper methods aren't available either](https://github.com/rust-vmm/vm-virtio/blob/main/crates/virtio-queue/src/descriptor.rs#L116).

This is being discussed by the Rust Community [here](https://github.com/rust-lang/rust/issues/67295).

For the time being, we can either ignore the affected doctests (`descriptor::Descriptor (line 21)` and `iterator::AvailIter (line 26)`) or ungate those features. Personally, I'm fine with either.

**Comment by lauralt** [comment]
This doesn't seem to be a problem anymore if the tests are run with `--all-features`, i.e. `cargo test --all-features`, `cargo test --doc --all-features`. Do you think there's another option we should consider regarding running the tests?

**Comment by slp** [comment]
@lauralt Yes, the `test-utils` feature works around the issue if you pass `--all-features` or `--features test-utils`, but it fails with bare `cargo test`, which can both be confusing for final users and problematic when packaging the crate in a distro (this is how I've noticed the issue).

**Comment by slp** [comment]
I managed to work around this for Fedora, so I guess it should be possible to do the same thing for other distros. Should we just simply document this somewhere?

**Comment by lauralt** [comment]
Yes, I'll document it.

**Comment by lauralt** [comment]
@slp I opened https://github.com/rust-vmm/vm-virtio/pull/137, please have a look!

**Comment by slp** [comment]
@lauralt I see that #137 has already been merged. Thanks a lot for working on this!
