### ISSUE TITLE
Tag a new release for virtio-queue

### ISSUE THREAD

**Issue by sboeuf** [rust-vmm/vm-virtio#145]
Could someone tag a new release for the `virtio-queue` crate so that Cloud Hypervisor can rely on it rather than using the latest commit from the main branch?
Apart from that, given that there are plans to update/simplify `virtio-queue`, this might/will bring breaking changes, therefore it might be a good idea to tag a release before going through any of that.

**Comment by andreeaflorescu** [comment]
Here is the PR: #146.

Btw, @sboeuf you also have permissions to do releases. Here is the read me on how to do that: https://github.com/rust-vmm/community/blob/main/docs/maintainers/crate_release.md. This should be useful in case someone from our team does not have the time to handle the releases.

**Comment by sboeuf** [comment]
@andreeaflorescu thanks for doing that, I appreciate it! And thanks for the documentation pointer, I'll take care of it myself next time :)

**Comment by andreeaflorescu** [comment]
No problem, people sometimes don't know that we documented a few processes, so I'm trying to spread the news :laughing: 

I forgot to update the Cargo.toml. Can you also check this PR #147

**Comment by andreeaflorescu** [comment]
Published v0.2.0: https://crates.io/crates/virtio-queue/0.2.0.

Closing this.
