### ISSUE TITLE
vsock: validate the size of the RX buffers against the max value

### ISSUE THREAD

**Issue by lauralt** [rust-vmm/vm-virtio#157]
We started working on validating the driver payload size against a maximum value (that will be set by the device, and negotiated with the driver). More details in [this virtio-spec patch](https://lists.oasis-open.org/archives/virtio-comment/202204/msg00010.html). For now we are doing the validation only [on the TX path](https://github.com/rust-vmm/vm-virtio/blob/7bfe164612bc4b4bea9c93591a4a578faaa8595b/crates/devices/virtio-vsock/src/packet.rs#L366). We should do the same on the RX one as well, i.e. validate that the size of the RX buffer that is corresponding to the payload is not exceeding the maximum allowed one (We can't validate the `len` header field on RX because its value is 0 when parsing the chain).

**Comment by uran0sH** [comment]
Working on it.

**Comment by lauralt** [comment]
Fixed by #160.
