### ISSUE TITLE
Tag a new release for virtio-queue

### ISSUE THREAD

**Issue by vireshk** [rust-vmm/vm-virtio#185]
Can someone tag a new release for virtio-queue ? The current one complains with different versions of vm-memory.

**Comment by vireshk** [comment]
I specifically need it for: https://github.com/rust-vmm/vhost/pull/114

**Comment by andreeaflorescu** [comment]
We plan to do some maintenance work this week, we can also capture the release as part of that. I would like us to switch to a newer Rust version as well.
