### ISSUE TITLE
Release new version of virtio-queue

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vm-virtio#197]
PR #196 fixed a potential self-DoS in the Virtio Queue implementation. We need to release a new version that customers can update to.

As the fix is on the hot path for handling requests, we would like to run the microbenchmarks from Virtio Queue. We will use this issue to track the results and impact.

Once we have a new release, I also think we should be reporting a vulnerability through RustSec: https://rustsec.org/ so that consumers of the virtio-queue crate are aware of the problem. @likebreath @rbradford @sboeuf would any of you like to do that? Otherwise, I can also report it myself.

**Comment by rbradford** [comment]
@andreeaflorescu Yes, a new release would be good. Coincidentally today is a scheduled release of Cloud Hypervisor but I think it's reasonable to delay until this crate gets released. I know in the past we've had issues with new releases of this crate requiring new releases of vhost, vhost-user-backend, etc? Do you think that will still be an issue in this case?

**Comment by rbradford** [comment]
On the RustSec note: I think it makes sense for a crate maintainer to do that.

**Comment by andreeaflorescu** [comment]
> @andreeaflorescu Yes, a new release would be good. Coincidentally today is a scheduled release of Cloud Hypervisor but I think it's reasonable to delay until this crate gets released. I know in the past we've had issues with new releases of this crate requiring new releases of vhost, vhost-user-backend, etc? Do you think that will still be an issue in this case?

The fix doesn't add a breaking change to the interface, so it shouldn't be a problem. I think the right approach is releasing this fix as a patch release with this since there's no API breaking change. This means that the dependency upgrade to virtio-queue v0.6.1 should be needed only at the Cloud Hypervisor level as the vhost crates depend on virtio-queue v0.6.0 (with caret requirements) which allows the crate to be update to any patch versions without publishing a new release.

**Comment by andreeaflorescu** [comment]
> On the RustSec note: I think it makes sense for a crate maintainer to do that.

Ok, I can do that once we publish the release.

**Comment by lauralt** [comment]
I ran the queue micro-benchmarks (which are essentially iterating over the available descriptor chains), and there is no change in performance.

Results:
- before applying the fix:
```
single chain (indirect=false)                                                                             
                        time:   [1.2828 µs 1.2835 µs 1.2842 µs]

multiple chains (indirect=false)                                                                             
                        time:   [2.1553 µs 2.1577 µs 2.1601 µs]

single chain (indirect=true)                                                                             
                        time:   [1.3028 µs 1.3037 µs 1.3046 µs]

multiple chains (indirect=true)                                                                             
                        time:   [3.4336 µs 3.4364 µs 3.4392 µs]
```
- after applying the fix:
```
single chain (indirect=false)                                                                             
                        time:   [1.2824 µs 1.2835 µs 1.2845 µs]
                        change: [-1.2209% -0.1621% +0.6733%] (p = 0.79 > 0.05)
                        No change in performance detected.

multiple chains (indirect=false)                                                                             
                        time:   [2.1709 µs 2.1729 µs 2.1748 µs]
                        change: [+0.6322% +0.7993% +0.9556%] (p = 0.00 < 0.05)
                        Change within noise threshold.

single chain (indirect=true)                                                                             
                        time:   [1.3049 µs 1.3059 µs 1.3069 µs]
                        change: [+0.0279% +0.1834% +0.3373%] (p = 0.02 < 0.05)
                        Change within noise threshold.

multiple chains (indirect=true)                                                                             
                        time:   [3.4645 µs 3.4668 µs 3.4691 µs]
                        change: [+0.8145% +0.9815% +1.1461%] (p = 0.00 < 0.05)
                        Change within noise threshold.
```
The term indirect means we have to process indirect descriptor tables as well, which is expected to be less performant.
I opened https://github.com/rust-vmm/vm-virtio/pull/198 for the release.

**Comment by lauralt** [comment]
I've published 0.6.1 release.

**Comment by andreeaflorescu** [comment]
Let's keep this issue open for tracking the RustSec advisory. i'll handle that tomorrow.

**Comment by lauralt** [comment]
We discussed during the sync meeting about adding this to RustSec and didn't find this necessary considering that the spec is not (yet) enforcing the check. Synced in private with @andreeaflorescu and she's okay with that. @rbradford shoould we close this issue then?
