### ISSUE TITLE
Master is Red - Buildkite Integration Tests

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vm-virtio#2]
The master branch of vm-virtio is red. It looks like it's due to this issue: https://github.com/rust-vmm/vmm-sys-util/issues/7

Buildkite log: https://buildkite.com/rust-vmm/vm-virtio-ci/builds/13

**Comment by sameo** [comment]
All green now, thanks @bonzini for fixing the vmm-sys-utils crate.

**Comment by andreeaflorescu** [comment]
Manually triggered build: https://buildkite.com/rust-vmm/vm-virtio-ci/builds/15
