### ISSUE TITLE
Where to obtain the descriptor index for Queue::add_used

### ISSUE THREAD

**Issue by slp** [rust-vmm/vm-virtio#20]
After commit 904662c3830b6df303d1c15108d96df395011b6c (@bonzini) removed the field `index` from `DescriptorChain`, I can't find a way to obtain the index from the last processed descriptor to pass it to `Queue::add_used`. Am I missing something or do we need that field back?

**Comment by alexandruag** [comment]
Hmm, how about switching the `AvailIter::Item` associated type from `DescriptorChain` to `(u16, DescriptorChain)`, where the `u16` value is the index of the first descriptor in the chain (the one that's read from the available ring)?

**Comment by jiangliu** [comment]
> After commit [904662c](https://github.com/rust-vmm/vm-virtio/commit/904662c3830b6df303d1c15108d96df395011b6c) (@bonzini) removed the field `index` from `DescriptorChain`, I can't find a way to obtain the index from the last processed descriptor to pass it to `Queue::add_used`. Am I missing something or do we need that field back?

There are still several pending patches, I will send them out soon.
Please refer to: https://github.com/cloud-hypervisor/vm-virtio/commit/55d3d26a76c3c3e276011f5f7c040196f8d46529
