### ISSUE TITLE
Separate queue test auxiliary logic and make it reusable

### ISSUE THREAD

**Issue by alexandruag** [rust-vmm/vm-virtio#23]
We have helper logic for mocking/initializing queue contents as part of unit tests, and some more mocking functionality is proposed as part of #19. It looks useful to consolidate and export this such that it can be used for all our tests, as well as external crates maybe. A short discussion on this topic happened [here](https://github.com/rust-vmm/vm-virtio/pull/19#discussion_r487828537).

**Comment by andreeaflorescu** [comment]
Is this fixed by #71?
