### ISSUE TITLE
Release virtio-queue v0.8.0

### ISSUE THREAD

**Issue by likebreath** [rust-vmm/vm-virtio#242]
With PR #240 landed last week, are there any blockers that stops us from cutting the release `virtio-queue v0.8.0`?

This release will enable its consumers (e.g. the `vhost` crate and Cloud Hypervisor) to bump its dependency to `vm-memory v0.11.0`.

**Comment by lauralt** [comment]
Yes we should release the new versions of virtio-queue and virtio-queue-ser. @slp can yo do the release since you've also published the PR and you are a codeowner? If not I can take care of it in the following days.

**Comment by slp** [comment]
Done, `virtio-queue v0.8.0` and `virtio-queue-ser 0.5.0` have been published on crates.io
