### ISSUE TITLE
Change OR to AND in licensing section of `virt-queue/Cargo.toml`

### ISSUE THREAD

**Issue by MatiasVara** [rust-vmm/vm-virtio#283]
This issue is in reference to https://github.com/rust-vmm/vm-virtio/pull/278#discussion_r1442891151 comment regarding the line: https://github.com/rust-vmm/vm-virtio/blob/a6365caae501c57acb22e6227a4659ffec328ea5/virtio-queue/Cargo.toml#L9

Should we change the OR to AND as most of the files in `virtio-queue/src/`?

Thanks,

**Comment by rbradford** [comment]
Yes, it should be AND.

**Comment by MatiasVara** [comment]
I'll submit a PR soon.
