### ISSUE TITLE
Query about device specific data in DescriptorChain

### ISSUE THREAD

**Issue by glitzflitz** [rust-vmm/vm-virtio#43]
So the [`DescriptorChain` from cloud-hypervisor's vm-virtio](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/22649c4a87900cf54f7833c7cc8b86364817c331/vm-virtio/src/queue.rs#L111)  contains `addr` and `len` fields for device specific data. Is there any way to get that data using this crate as the [`DescriptorChain` in this crate](https://github.com/rust-vmm/vm-virtio/blob/7b5fd44d802408212d746eaa3e41ad2f22477a7a/src/queue.rs#L146) does not have those fields?

**Comment by alexandruag** [comment]
Hi, the `DescriptorChain` in this crate is basically an iterator that yields `Descriptor`s via `next()`. The `Descriptor` objects themselves have methods to retrieve the address and length. Are these the values you were referring to?

**Comment by glitzflitz** [comment]
@alexandruag Yeah those were the values I was looking for. Thanks!
