### ISSUE TITLE
Convert vm-virtio to a workspace

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vm-virtio#44]
If we convert this repository to a workspace, then we can have all vm-virtio components published from the repositories. This allows us to test the interoperability of the various components (virtio queues, implementation of virtio-block/net/vsock/others), while still being able to publish them as individual crates. It should also make it easier to change the interfaces (up to the point where we actually get them settled in) because we can add all required changes in one PR.

**Comment by jiangliu** [comment]
That's great, so we could have virtio-queue, virtio-net, virtio-blk etc.

**Comment by krady21** [comment]
I'll try to tackle this. I have two directory structures in mind:
```
vm-virtio
+- virtio-queue
+- virtio-device
+- devices
|   +- virtio-blk
|   +- virtio-net
```
or a flatter one:
```
vm-virtio
+- virtio-queue
+- virtio-device
+- virtio-blk
+- virtio-net
```
I lean more towards the first one. Which one would you prefer?
Another question worth asking would be whether to add all the device agnostic code and queue implementation into the same crate (virtio-common maybe).

**Comment by andreeaflorescu** [comment]
I haven't tried out option number 1. Does it work with workspace? It looks good to me.

I think the reason for separate crates for devices agnostic code and queues was that people might end up consuming queues without consuming the devices as well. For now I'd say to keep them separate.

Another thing that we were considering was to have all code under `src/` because otherwise the repository tends to be clutter with other unrelated files. That would mean that we have a structure like:

```
README.md
CONTRIBUTING.md
rust-vmm-ci/
other_files_that_are_repo_specific
src/
+- virtio-queues
+- virtio-device
+- devices
.....
```

Does that make sense?

**Comment by alexandruag** [comment]
Hmm, are individual devices still individual crates with this approach?

**Comment by krady21** [comment]
> Hmm, are individual devices still individual crates with this approach?

I would think so.

**Comment by alexandruag** [comment]
Looks good then.
