### ISSUE TITLE
 Identify existing mock-up approaches

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vm-virtio#60]
We should take a look at existing mock-up approaches (both in vm-virtio, and other projects that use virtio devices in Rust). These should be documented in this issue so we can take a more informed decision when starting the design of the mocking framework.

**Comment by krady21** [comment]
There are currently several projects that offer mocking interfaces for virtio queues and descriptors.

* `vm-virtio`: There are two interfaces used for mocking virtio queue operations usually done by the driver: `MockSplitQueue` (used for benchmarks) and `VirtQueue` (used for unit tests). They are not to be confused with the Queue struct, which is used from the device's perspective. 
* `cloud-hypervisor` and `firecracker`: Both projects use a structure called `VirtQueue` that is similar to the one used in `vm-virtio`.
* `crosvm`: Crosvm doesn't seem to use a different structure for imitating the driver specific interaction with the virtio queue, instead it allocates some GuestMemory, which is then used to directly create the struct `Queue` (the queue from the device's perspective). The virtqueue_fuzzer implemented by `crosvm` could provide further hints for improving the current mock interface.  

More improvements could be added to facilitate the creation of Descriptor chains, as the current interfaces require manual creation and storing of each descriptor. Another improvement would consist of  a method that populates the underlying memory areas, which the descriptors are pointing to.
