### ISSUE TITLE
[virtio-queue] document `unsafe impl` safety

### ISSUE THREAD

**Issue by lauralt** [rust-vmm/vm-virtio#99]
We have two `unsafe impl`s: https://github.com/rust-vmm/vm-virtio/blob/main/crates/virtio-queue/src/lib.rs#L144, https://github.com/rust-vmm/vm-virtio/blob/main/crates/virtio-queue/src/lib.rs#L385 that should be documented on why they are safe.

**Comment by bonzini** [comment]
The description for ByteValued says

> A type `T` is `ByteValued` if and only if it can be initialized by reading its contents from a byte array.  This is generally true for all plain-old-data structs.  It is notably not true for any type that includes a reference.
>
> Implementing this trait guarantees that it is safe to instantiate the struct with random data.

So the description would be that 1) `Descriptor` or `VirtqElem` structs *are* plain-old-data 2) all accesses through safe vm-memory API will validate any garbage that could be included in there. Is that correct or am I missing something?
